name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (including dev)
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Lint with flake8
        run: |
          flake8 sample_pipeline.py --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 sample_pipeline.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Check formatting with black
        run: |
          black --check sample_pipeline.py

      - name: Type check with mypy
        run: |
          mypy sample_pipeline.py --ignore-missing-imports

      - name: Test with pytest
        run: |
          pytest --cov=sample_pipeline --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
